name: finance_tracker
description: "A cash App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.0
  fpdart: ^1.1.0
  get_it: ^7.7.0
  supabase_flutter: ^2.5.6
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logos/
