name: finance_tracker
description: "A cash App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.0
  fpdart: ^1.1.0
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.5.6
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.2.3
  intl: ^0.17.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.0
  provider: ^6.1.2
  charts_flutter: ^0.12.0
  local_auth: ^2.2.0
  equatable: ^2.0.5
  uuid: ^4.4.2
  flutter_local_notifications: ^17.2.1+1
  timezone: ^0.9.4
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  syncfusion_flutter_xlsio: ^21.2.3
  path_provider: ^2.1.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  path: ^1.9.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  flutter_animate: ^4.5.0
  fl_chart: ^0.68.0
  flutter_file_dialog: ^3.0.2
  #isar: ^4.0.0-dev.14

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logos/
    - .env
    - assets/images/
